app_users/urls.py
from .views import LoginView, ProfileView, LogoutView, GoogleCallbackView, GithubCallbackView, LinkedinCallbackView
from django.urls import path

app_name = 'users'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('auth/google/callback/', GoogleCallbackView.as_view(), name='google_callback'),
    path('auth/github/callback/', GithubCallbackView.as_view(), name='github_callback'),
    path('auth/linkedin/callback/', LinkedinCallbackView.as_view(), name='linkedin_callback'),
]   

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from app_users.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),

    # Local apps
    path('users/', include('app_users.urls', namespace='users')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_users/models.py
from django.db import models
from django.contrib.auth.models import User

# username, password, email, first_name, last_name, is_active, is_staff, is_superuser, last_login, date_joined

class Profile(models.Model):
    """
    Model to store extra information about the user
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    provider = models.CharField(max_length=50, blank=True, null=True) # Provider name (Google, Github, etc)
    token_details = models.TextField(blank=True, null=True) # Token details JSON format
    avatar = models.URLField(blank=True, null=True) # URL to the user's profile picture
    extra_info = models.TextField(blank=True, null=True) # Information about the user JSON format
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

app_users/views.py
import json
from django.views.generic import TemplateView
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.contrib import messages
from .oauth import google_oauth2, github_oauth2, linkedin_oauth2
from .models import Profile
# Create your views here.

class IndexView(TemplateView):

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('users:profile')
        else:
            return redirect('users:login')

class ProfileView(TemplateView):
    template_name = 'app_users/profile.html'

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('users:login')
        return super().get(request, *args, **kwargs)

class LoginView(TemplateView):
    template_name = 'app_users/login.html'
    
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('users:profile')
        
        provider = request.GET.get('provider')
        if provider == 'google':
            auth_url, state = google_oauth2.get_auth_url()
            request.session['state'] = state
            return redirect(auth_url)
        elif provider == 'github':
            auth_url, state = github_oauth2.get_auth_url()
            request.session['state'] = state
            return redirect(auth_url)
        elif provider == 'linkedin':
            auth_url, state = linkedin_oauth2.get_auth_url()
            request.session['state'] = state
            return redirect(auth_url)
        return super().get(request, *args, **kwargs)

class GoogleCallbackView(TemplateView):

    def get(self, request, *args, **kwargs):
        if request.GET.get('state') != request.session.get('state'):
            messages.error(request, 'Invalid state')
            return redirect('users:login')
        token = google_oauth2.get_token(request.GET.get('code'))

        if token is None:
            messages.error(request, 'Invalid token')
            return redirect('users:login')
        
        user_info = google_oauth2.get_user_info()
        
        email = user_info.get('email')
        given_name = user_info.get('given_name')
        family_name = user_info.get('family_name')
        picture = user_info.get('picture')
        provider = 'Google'

        if User.objects.filter(username=email).exists():
            user = get_object_or_404(User, username=email)
        else:
            user = User.objects.create_user(username=email, email=email,\
                                                first_name=given_name, last_name=family_name)
            Profile.objects.create(user=user, token_details=token, provider=provider,\
                                                 avatar = picture, extra_info=json.dumps(user_info))
        login(request, user)
        messages.success(request, 'Welcome {}'.format(user.first_name))
        return redirect('users:profile')
    
    def post(self, request, *args, **kwargs):
        return redirect('users:login')
    
    def put(self, request, *args, **kwargs):
        return redirect('users:login')
    
    def delete(self, request, *args, **kwargs):
        return redirect('users:login')
    
    def patch(self, request, *args, **kwargs):
        return redirect('users:login')
    
class GithubCallbackView(TemplateView):
        
    def get(self, request, *args, **kwargs):
        if request.GET.get('state') != request.session.get('state'):
            messages.error(request, 'Invalid state')
            return redirect('users:login')
        token = github_oauth2.get_token(request.GET.get('code'))

        if token is None:
            messages.error(request, 'Invalid token')
            return redirect('users:login')
    
        user_info = github_oauth2.get_user_info(token.get('access_token'))
        
        email = user_info.get('email')
        name = user_info.get('name')
        avatar = user_info.get('avatar_url')
        provider = 'Github'
        
        if User.objects.filter(username=email).exists():
            user = get_object_or_404(User, username=email)
        else:
            user = User.objects.create_user(username=email, email=email,\
                                                first_name=name)
            Profile.objects.create(user=user, token_details=token, provider=provider,\
                                                avatar = avatar, extra_info=json.dumps(user_info))
        login(request, user)
        messages.success(request, 'Welcome {}'.format(user.first_name))
        return redirect('users:profile')
    
    def post(self, request, *args, **kwargs):
        return redirect('users:login')
    
    def put(self, request, *args, **kwargs):
        return redirect('users:login')
    
    def delete(self, request, *args, **kwargs):
        return redirect('users:login')
    
    def patch(self, request, *args, **kwargs):
        return redirect('users:login')

class LinkedinCallbackView(TemplateView):
            
    def get(self, request, *args, **kwargs):
        if request.GET.get('state') != request.session.get('state'):
            messages.error(request, 'Invalid state')
            return redirect('users:login')
        
        error = request.GET.get('error', None)
        if error:
            messages.error(request, error)
            return redirect('users:login')
        
        code = request.GET.get('code')
        if code is None:
            messages.error(request, 'Invalid code')
            return redirect('users:login')

        token = linkedin_oauth2.get_token(code)

        if token is None:
            messages.error(request, 'Invalid token')
            return redirect('users:login')
        
        access_token = token.get('access_token')

        user_info = linkedin_oauth2.get_user_info(access_token)
        if user_info is None:
            messages.error(request, 'Invalid user info')
            return redirect('users:login')

        email = user_info.get('email')
        given_name = user_info.get('given_name')
        family_name = user_info.get('family_name')
        avatar = user_info.get('picture')
        provider = 'Linkedin'
        import requests
        resp = requests.get(avatar, stream=True)
        if resp.status_code == 200:
            with open(f'static/images/{email}.jpg', 'wb') as f:
                f.write(resp.content)
        
        if User.objects.filter(username=email).exists():
            user = get_object_or_404(User, username=email)
        else:
            user = User.objects.create_user(username=email, email=email,\
                                                first_name=given_name, last_name=family_name)
            Profile.objects.create(user=user, token_details=token, provider=provider,\
                                                avatar = avatar, extra_info=json.dumps(user_info))
        login(request, user)
        messages.success(request, 'Welcome {}'.format(user.first_name))
        return redirect('users:profile')
    
    def post(self, request, *args, **kwargs):
        return redirect('users:login')
    
    def put(self, request, *args, **kwargs):
        return redirect('users:login')
    
    def delete(self, request, *args, **kwargs):
        return redirect('users:login')
    
    def patch(self, request, *args, **kwargs):
        return redirect('users:login')

class LogoutView(TemplateView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            logout(request)
            messages.success(request, 'You have been logged out')
        return redirect('users:login')
    
    def post(self, request, *args, **kwargs):
        return redirect('users:login')
    
    def put(self, request, *args, **kwargs):
        return redirect('users:login')
    
    def delete(self, request, *args, **kwargs):
        return redirect('users:login')
    
    def patch(self, request, *args, **kwargs):
        return redirect('users:login')

templates/app_users/login.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ingreso o Registro</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <div class="container text-center p-4">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                {% include 'includes/messages.html' %}
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h5 class="card-title">Autenticación</h5>
                        <h6 class="card-subtitle mb-2 text-body-secondary">Ingresa o Registrate</h6>
                        <p class="card-text">Con diferentes redes sociales</p>
                        <a href="?provider=google" class="card-link text-danger fs-2 me-3"><svg
                                xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                                class="bi bi-google" viewBox="0 0 16 16">
                                <path
                                    d="M15.545 6.558a9.4 9.4 0 0 1 .139 1.626c0 2.434-.87 4.492-2.384 5.885h.002C11.978 15.292 10.158 16 8 16A8 8 0 1 1 8 0a7.7 7.7 0 0 1 5.352 2.082l-2.284 2.284A4.35 4.35 0 0 0 8 3.166c-2.087 0-3.86 1.408-4.492 3.304a4.8 4.8 0 0 0 0 3.063h.003c.635 1.893 2.405 3.301 4.492 3.301 1.078 0 2.004-.276 2.722-.764h-.003a3.7 3.7 0 0 0 1.599-2.431H8v-3.08z" />
                            </svg></a>
                        <a href="?provider=github" class="card-link text-dark fs-2 me-3"><svg xmlns="http://www.w3.org/2000/svg"
                                width="25" height="25" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                                <path
                                    d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8" />
                            </svg></a>
                        <a href="?provider=linkedin" class="card-link fs-2"><svg xmlns="http://www.w3.org/2000/svg" width="25"
                                height="25" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
                                <path
                                    d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z" />
                            </svg></a>
                    </div>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

templates/app_users/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ingreso o Registro</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <div class="container text-center p-4">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                {% include 'includes/messages.html' %}
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h5 class="card-title">Usuario autenticado con {{request.user.profile.provider}}</h5>
                        <h6 class="card-subtitle mb-2 text-body-secondary">{{request.user.first_name}}
                            {{request.user.last_name}}</h6>
                        <p class="card-text">{{request.user.email}}</p>

                        {% if request.user.profile.provider == 'linkedin' %}
                        <img src="/static/images/{{request.user.email}}.jpg" class="border border-primary"
                            style="border-radius: 10px;" alt="Avatar {{request.user.first_name}}">
                        {% else %}
                        <img src="{{request.user.profile.avatar}}" alt="Avatar {{request.user.first_name}}"
                            class="border border-primary" style="border-radius: 10px;" width="120">
                        {% endif %}
                        <hr>
                        <a href="{% url 'users:logout' %}" class="card-link text-danger me-3">Cerrar sesión</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>